version:                   '3.1'
services:
  files:
    image:                 nextcloud
    restart:               always
    ports:
      - 8080:80
    volumes:
      - files_data:        /var/www/html/data
      - files_config:      /var/www/html/config

volumes:
  files_data:
    external:              true
  files_config:
    external:              true
